/* ============================================================
   QUOTES — this is the only file you should need to edit.

   Add one line per quote, formatted exactly like the examples:
     { text: "The quote goes here", answer: "A" },
     { text: "Another quote here",  answer: "B" },

   - "answer" must be "A" or "B" — A = partnerA (Dani), B = partnerB (Michael),
     as set in index.html (CONFIG.partnerA / CONFIG.partnerB).
   - Keep the quotes inside straight double quotes "like this".
   - Don't forget the comma at the end of each line.
   - You can paste in all ~200 — the quiz will randomly pick
     from whichever ones are in this list each time it's played.
   ============================================================ */

const QUOTES = [
  { text: "DON'T DO BETTER!", answer: "A" },
  { text: "Ignore the lunchbox... These are my shorts...", answer: "B" },
  { text: "You can do what you can, but you can't do what you can't.", answer: "B" },
  { text: "Believe it or not, I actually really like food...", answer: "A" },
  { text: "I think his lollipop was on fire.", answer: "B" },
  { text: "Note to self, I will never get you used socks...", answer: "A" },
  { text: "Don't look at me at a funeral...", answer: "A" },
  { text: "Can I take your head off?", answer: "B" },
  { text: "I enjoy watching you struggle", answer: "A" },
  { text: "you're my favorite drug", answer: "B" },
  { text: "You are the gorgeous human in your life", answer: "A" },
  { text: "... I'm eating cheese... It's good cheese...", answer: "A" },
  { text: "Do you want some... floor beans??", answer: "A" },
  { text: "You can have a noodle... this is why he's chunky", answer: "A" },
  { text: "You smell a lot better than that trash.", answer: "B" },
  { text: "I forget you eat things weird.", answer: "A" },
  { text: "Just lick it off and I'll put it back in my pocket.", answer: "A" },
  { text: "I can fix plumbing. I can't fix when people leak.", answer: "B" },
  { text: "We got options man...What are the options?", answer: "A" },
  { text: "I'm a big booger thank you very much.", answer: "B" },
  { text: "I actually have a spoon...You can see my spit on it...", answer: "A" },
  { text: "You should be a voice actor... for a car...", answer: "A" },
  { text: "I need to go set something on fire...", answer: "B" },
  { text: "I would prefer to not wake up the whole house with my belly button...", answer: "B" },
  { text: "Have you found my kidney??", answer: "A" },
  { text: "Today?? It's not today yet...", answer: "A" },
  { text: "You smell better than a breakfast burrito.", answer: "B" },
  { text: "I cannot with stinky people...", answer: "A" },
  { text: "Yeah! Why do people... not do hygiene??", answer: "B" },
  { text: "How attractive is it that I can fit a whole game in my pocket??", answer: "B" },
  { text: "I wanna get to know youuuu... Not Jesus... oh wait no, that's not what I meantttt", answer: "A" },
  { text: "it's a compliment, I promise!!", answer: "B" },
  { text: "That didn't taste good to my brain", answer: "B" },
  { text: "Yeah, you definitely don't yawn like a normal person...", answer: "A" },
  { text: "hey, are you looking for my kidney?", answer: "A" },
  { text: "it's sweet... But in a manly way", answer: "B" },
  { text: "our pants, but my pants.", answer: "B" },
  { text: "You can keep your socks on and I can keep my socks on, and we'll both be happy", answer: "B" },
  { text: "I think you smell better than a store... you smell better than Walmart.", answer: "A" },
  { text: "I hope you have fun wearing our pants!", answer: "A" },
  { text: "eat your frickin' sandwich!", answer: "A" },
  { text: "are we getting high??", answer: "B" },
  { text: "If I was Jesus I would be mad right now.", answer: "B" },
  { text: "I am NOT inviting you!!", answer: "A" },
  { text: "now all the mints have been touched", answer: "A" },
  { text: "Okayyy... when the car is on I won't touch your kidneys!!", answer: "A" },
  { text: "Don't do it because of my beard.", answer: "B" },
  { text: "I can't buy smelly things and not smell them.", answer: "A" },
  { text: "If you had a bald head I would call it beautiful...please don't shave your head.", answer: "A" },
  { text: "I better not honk that with my bum.", answer: "B" },
  { text: "Please don't threaten your sister with my kisses...", answer: "B" },
  { text: "I've only ever shared rooms with guys.", answer: "B" },
  { text: "I really hope that your thumbs aren't the same size when you're resurrected.", answer: "A" },
  { text: "I think dumb people just don't get up early.", answer: "B" },
  { text: "I need to lotion my elbows...", answer: "A" },
  { text: "I put lotion on my elbows!", answer: "B" },
  { text: "I like the chunks. They're like little surprises.", answer: "B" },
  { text: "You're pretty and it makes me high.", answer: "B" },
  { text: "Have I told you about my calves...about the hair...that's gone?", answer: "B" },
  { text: "I can't feel your spine very well with my elbow.", answer: "A" },
  { text: "I burped and my head hit the freezer.", answer: "B" },
  { text: "All raw broccoli is bad broccoli", answer: "A" },
  { text: "Nope—soggy broccoli... I don't want a nightmare.", answer: "A" },
  { text: "ah, they were hiding the Italian from me... under the table...", answer: "A" },
  { text: "GOOD! they can know I'm in LOVE.", answer: "A" },
  { text: "Is that a turd or a leaf? ...let's play a game!!!", answer: "B" },
  { text: "I was looking at him... not your toes...", answer: "A" },
  { text: "Do you want me to find your other kidney??", answer: "A" },
  { text: "You need to lotionize your elbows...", answer: "A" },
  { text: "Think goodness you're not a buffalo guy!", answer: "A" },
  { text: "I would be grumpy if I was awake right now.", answer: "B" },
  { text: "I stink good.", answer: "B" },
  { text: "I swear I've slapped you before...have I not??", answer: "A" },
  { text: "yeah, I function like a normal human being...", answer: "B" },
  { text: "But you're not a vampire... so, it doesn't count...", answer: "A" },
  { text: "Ya know...The Easter Bunny isn't Jesus.", answer: "B" },
  { text: "America doesn't have any oceans..", answer: "A" },
  { text: "It's nice to rub your back with a spatula.", answer: "B" },
  { text: "I ain't never seen a waxing gibbous like that", answer: "A" },
  { text: "notice how I'm not choking on it...", answer: "A" },
  { text: "You have a very attractive brain.", answer: "A" },
  { text: "I am really good at hiding how illiterate I am.", answer: "B" },
  { text: "that's right, my head does come off...", answer: "A" },
  { text: "I would never want to factory reset you...", answer: "A" },
  { text: "I am able to poop in other places than my own home.", answer: "B" },
  { text: "I'm sorry I disgusted you today...", answer: "B" },
  { text: "It's pretty good that I can sound like a small Indian kid.", answer: "B" },
  { text: "I look like drunk Cleopatra...", answer: "A" },
  { text: "I can loosen it with my chin—no problem!", answer: "A" },
  { text: "Make Dalmatians popular again.", answer: "B" },
  { text: "I'm kinda sad that didn't backfire on you...", answer: "A" },
  { text: "I don't think if I grow my hair out I'll look like Jesus.", answer: "B" },
  { text: "I'm the kind of guy who changes the toilet paper roll.", answer: "B" },
  { text: "You think I would be used to having hair in my nose", answer: "B" },
  { text: "we don't believe in reincarnation, hun.", answer: "A" },
  { text: "I'm following the man with the cheese", answer: "A" },
  { text: "Your hair smells like bacon", answer: "A" },
  { text: "I've got better gas mileage than you... Cause I'm walking.", answer: "B" },
  { text: "Did you hide your kidneys from me??!", answer: "A" },
  { text: "Thanks for letting me find your kidneys.", answer: "A" },
  { text: "And you didn't invite me??! You didn't think that I would've wanted to go to Mercury??", answer: "A" },
  { text: "I think you put your mouth in my finger... Wait...", answer: "A" },
  { text: "I'm a weird looking fire truck", answer: "B" },
  { text: "I didn't hit her... I just threatened...", answer: "A" },
  { text: "I appreciate your warm-abilities.", answer: "B" },
  { text: "you are no longer free from someone poking your bruises...", answer: "A" },
  { text: "No seducing me before we put the ice cream in the freezer...", answer: "A" },
  { text: "Sorry, you have my neck hair on your hand.", answer: "B" },
  { text: "It's not fair that you have two arms...", answer: "A" },
  { text: "your toes bend weird.", answer: "A" },
  { text: "I usually lick things like this but I can't lick my elbow.", answer: "B" },
  { text: "I think the easy no's are yes's though.", answer: "A" },
  { text: "I love to watch your lips wiggle...", answer: "A" },
  { text: "Now all we need is his last name... then we can steal his identity!", answer: "A" },
  { text: "...a cooler was driving that truck...", answer: "A" },
  { text: "why does that person have ears???", answer: "B" },
  { text: "Forgive my misunderspeaking.", answer: "A" },
  { text: "Where did my Jesus go??", answer: "B" },
  { text: "If you loved me, you would let me die of dehydration...", answer: "A" },
  { text: "Don't lick it when you have spicy on your tongue", answer: "B" },
  { text: "I'll be hugging you until you die.", answer: "A" },
  { text: "Well. I guess I just won't use the bathroom for a week.", answer: "B" },
  { text: "Did the sleigh bed getchya??", answer: "A" },
  { text: "Do you want the kiss? Or do you want to get locked out...?", answer: "A" },
  { text: "Is your hand warm? I forgot I was sitting on it.", answer: "B" },
  { text: "Thank you for kissing my elbow.", answer: "A" },
  { text: "You can't wish on eyebrow hairs...", answer: "A" },
  { text: "My elbow bone is about the length of my short thumb.", answer: "B" },
  { text: "He gets a blessed chimichanga and you don't... that's just how it is...", answer: "A" },
  { text: "I am NOT eating dryer lint for you", answer: "B" },
  { text: "... If you quote that entire movie, I will murder you...", answer: "A" },
  { text: "does that tickle too? Or are you just scared?", answer: "A" },
  { text: "you were close... You got the first letter...", answer: "A" },
  { text: "I've never had that in... It's been like years...", answer: "B" },
  { text: "that would be a weird occupation. 'I pee for other people.'", answer: "B" },
  { text: "Okay let's go inside so we don't run over an undisabled person and make them disabled.", answer: "B" },
  { text: "Texans are just America's Australians...", answer: "B" },
  { text: "I love how you assume everyone's a male, until it comes to Grandma...", answer: "A" },
  { text: "Oops, you dropped the blood...", answer: "A" },
  { text: "My brain tooted.", answer: "A" },
  { text: "your bum sounds like a car engine.", answer: "A" },
  { text: "bro, what are we doing?! Let's quit our jobs and sell our pee!!", answer: "A" },
  { text: "You know how some people say that your dogs are waiting for you in heaven??...are the dinosaurs waiting for us??", answer: "A" },
  { text: "No, I'm not going to mug him for his underwear.", answer: "B" },
];